In [2]:
import pandas as pd
import seaborn as sns 
import numpy as np
import matplotlib.pyplot as plt
import warnings
%matplotlib inline
from pandas import ExcelWriter
from pandas import ExcelFile

#Removing warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [7]:
snapshot = pd.read_excel("data/207101 - Snapshot of Australia.xls", sheet_name = None)
snapshot

OrderedDict([('Contents',
                                    Australian Bureau of Statistics  \
              0   2071.0 Census of Population and Housing: Refle...
              1    Released at 11.30am (Canberra time) 20 July 2017
              2                                                 NaN
              3                                                 NaN
              4                                                 NaN
              5                                                 NaN
              6                                                 NaN
              7                                                 NaN
              8                                                 NaN
              9                                                 NaN
              10                                                NaN
              11                                                NaN
              12                                                NaN
              13                                                NaN
              14                                                NaN
              15                                                NaN
              16                                                NaN
              17                                                NaN
              18                                                NaN
              19                                                NaN
              20                                                NaN
              21                                                NaN
              22                                                NaN
              23                                                NaN
              24                                                NaN
              25                                                NaN
              26                                                NaN
              27                                                NaN
              28                                                NaN
              29                                                NaN
              30                                                NaN
              31                                                NaN
              32                                                NaN
              33                                                NaN
              34                                                NaN
              35                                                NaN
              36                                                NaN
              37                                                NaN
              38                                                NaN
              39                                                NaN

                                                         Unnamed: 1  \
              0                                                 NaN
              1                                                 NaN
              2                                                 NaN
              3                                            Contents
              4                                              Tables
              5                                                   1
              6                                                   2
              7                                                   3
              8                                                   4
              9                                                   5
              10                                                  6
              11                                                  7
              12                                                  8
              13                                                  9
              14                                                 10
              15                                                 11
              16                                                 12
              17                                                 13
              18                                                 14
              19                                                 15
              20                                                 16
              21                                                 17
              22                                                 18
              23                                                 19
              24                                                 20
              25                                  Explanatory Notes
              26                                                NaN
              27                                                NaN
              28    More information available from the ABS website
              29                                                NaN
              30  Reflecting Australia - Stories from the Census...
              31                                            Summary
              32                                 Explanatory Notes
              33                                                NaN
              34                                                NaN
              35                                          Inquiries
              36                                                NaN
              37  Further information about these and related st...
              38                                                NaN
              39                   Â© Commonwealth of Australia 2017

                                                         Unnamed: 2
              0                                                 NaN
              1                                                 NaN
              2                                                 NaN
              3                                                 NaN
              4                                                 NaN
              5   State and Territory of Usual Residence - 1966-...
              6   Greater Capital City Statistical Areas - 2011 ...
              7                         Age and Sex - 2011 and 2016
              8   Indigenous Status and State and Territory of U...
              9   Indigenous Status and Greater Capital City Sta...
              10          Indigenous Status and Age - 2011 and 2016
              11  Country of Birth of Person and State and Terri...
              12  Selected Countries of Birth of Person and Stat...
              13        Religious Affiliation - 1966, 1991 and 2016
              14  Total Personal Income (Weekly) and State and T...
              15  Dwelling Type by State and Territory of Enumer...
              16  Household Composition and State and Territory ...
              17  Sex of Lone Persons and Age, Lone Person House...
              18  State and Territory of Enumeration, Average Nu...
              19  Family Composition and State and Territory of ...
              20  Sex of Lone Parent and State and Territory of ...
              21  Same-Sex Couple Indicator and Count of All Chi...
              22  Relationship in Household (for Husbands, wives...
              23  Dwelling Structure and State and Territory of ...
              24  Tenure type and State and Territory of Enumera...
              25                                                NaN
              26                                                NaN
              27                                                NaN
              28                                                NaN
              29                                                NaN
              30                                                NaN
              31                                                NaN
              32                                                NaN
              33                                                NaN
              34                                                NaN
              35                                                NaN
              36                                                NaN
              37                                                NaN
              38                                                NaN
              39                                                NaN  ),
             ('Table 1',
                                    Australian Bureau of Statistics  Unnamed: 1  Unnamed: 2  \
              0   2071.0 Census of Population and Housing: Refle...         NaN         NaN
              1    Released at 11.30am (Canberra time) 20 July 2017         NaN         NaN
              2   Table 1 State and Territory of Usual Residence...         NaN         NaN
              3                                                 NaN         NaN         NaN
              4                                                 NaN      1966.0      1991.0
              5              State and Territory of Usual Residence         NaN         NaN
              6                                     New South Wales   4237900.0   5714974.0
              7                                            Victoria   3220217.0   4287877.0
              8                                          Queensland   1674324.0   2887505.0
              9                                     South Australia   1094984.0   1408623.0
              10                                  Western Australia    848100.0   1576334.0
              11                                           Tasmania    371436.0    456219.0
              12                                 Northern Territory     56504.0    159300.0
              13                       Australian Capital Territory     96032.0    280868.0
              14                                       Australia(b)  11599497.0  16771700.0
              15                                                NaN         NaN         NaN
              16   This table is based on place of usual residence.         NaN         NaN
              17                                                NaN         NaN         NaN
              18  (a) Usual Residence Census counts. Excludes ov...         NaN         NaN
              19  (b) Total includes Other Territories. Other Te...         NaN         NaN
              20                                                NaN         NaN         NaN
              21  Please note that there are small random adjust...         NaN         NaN
              22                                                NaN         NaN         NaN
              23                   Â© Commonwealth of Australia 2017         NaN         NaN

                  Unnamed: 3  Unnamed: 4  Unnamed: 5
              0          NaN         NaN         NaN
              1          NaN         NaN         NaN
              2          NaN         NaN         NaN
              3          NaN         NaN         NaN
              4       2006.0      2011.0      2016.0
              5          NaN         NaN         NaN
              6    6549174.0   6917656.0   7480228.0
              7    4932421.0   5354040.0   5926624.0
              8    3904531.0   4332738.0   4703193.0
              9    1514340.0   1596570.0   1676653.0
              10   1959087.0   2239171.0   2474410.0
              11    476481.0    495352.0    509965.0
              12    192899.0    211944.0    228833.0
              13    324034.0    357218.0    397397.0
              14  19855288.0  21507717.0  23401892.0
              15         NaN         NaN         NaN
              16         NaN         NaN         NaN
              17         NaN         NaN         NaN
              18         NaN         NaN         NaN
              19         NaN         NaN         NaN
              20         NaN         NaN         NaN
              21         NaN         NaN         NaN
              22         NaN         NaN         NaN
              23         NaN         NaN         NaN  ),
             ('Table 2',
                                    Australian Bureau of Statistics  Unnamed: 1  Unnamed: 2
              0   2071.0 Census of Population and Housing: Refle...         NaN         NaN
              1    Released at 11.30am (Canberra time) 20 July 2017         NaN         NaN
              2   Table 2 Greater Capital City Statistical Areas...         NaN         NaN
              3                                                 NaN         NaN         NaN
              4                                                 NaN      2011.0      2016.0
              5              Greater Capital City Statistical Areas         NaN         NaN
              6                                      Greater Sydney   4391673.0   4823991.0
              7                                   Greater Melbourne   3999980.0   4485211.0
              8                                    Greater Brisbane   2065998.0   2270800.0
              9                                    Greater Adelaide   1225234.0   1295714.0
              10                                      Greater Perth   1728865.0   1943858.0
              11                                     Greater Hobart    211655.0    222356.0
              12                                     Greater Darwin    120586.0    136828.0
              13                       Australian Capital Territory    356586.0    396857.0
              14                       Total Greater Capital Cities  14100577.0  15575618.0
              15                                                NaN         NaN         NaN
              16   This table is based on place of usual residence.         NaN         NaN
              17                                                NaN         NaN         NaN
              18  (a) Usual Residence Census counts. Excludes ov...         NaN         NaN
              19                                                NaN         NaN         NaN
              20  Please note that there are small random adjust...         NaN         NaN
              21                                                NaN         NaN         NaN
              22                   Â© Commonwealth of Australia 2017         NaN         NaN),
             ('Table 3',
                                    Australian Bureau of Statistics Unnamed: 1 Unnamed: 2  \
              0   2071.0 Census of Population and Housing: Refle...        NaN        NaN
              1    Released at 11.30am (Canberra time) 20 July 2017        NaN        NaN
              2   Table 3 Age and Sex, Count of persons(a) - 201...        NaN        NaN
              3                                                 NaN        NaN        NaN
              4                                                 NaN        NaN       2011
              5                                                 NaN       Unit      Males
              6                                          Median age      years         36
              7                                                 NaN        NaN        NaN
              8                                           Age group        NaN        NaN
              9                                           0-4 years        no.     729969
              10                                          5-9 years        no.     694561
              11                                        10-14 years        no.     703308
              12                                        15-19 years        no.     722378
              13                                        20-24 years        no.     741120
              14                                        25-29 years        no.     754466
              15                                        30-34 years        no.     719654
              16                                        35-39 years        no.     747117
              17                                        40-44 years        no.     754569
              18                                        45-49 years        no.     740962
              19                                        50-54 years        no.     711741
              20                                        55-59 years        no.     637839
              21                                        60-64 years        no.     597885
              22                                        65-69 years        no.     455420
              23                                        70-74 years        no.     342691
              24                                        75-79 years        no.     252930
              25                                        80-84 years        no.     188242
              26                                  85 years and over        no.     139162
              27                                              Total        no.   10634014
              28                                                NaN        NaN        NaN
              29   This table is based on place of usual residence.        NaN        NaN
              30                                                NaN        NaN        NaN
              31  (a) Usual Residence Census counts. Excludes ov...        NaN        NaN
              32                                                NaN        NaN        NaN
              33  Please note that there are small random adjust...        NaN        NaN
              34                                                NaN        NaN        NaN
              35                   Â© Commonwealth of Australia 2017        NaN        NaN

                 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7
              0         NaN        NaN        NaN        NaN        NaN
              1         NaN        NaN        NaN        NaN        NaN
              2         NaN        NaN        NaN        NaN        NaN
              3         NaN        NaN        NaN        NaN        NaN
              4         NaN        NaN       2016        NaN        NaN
              5     Females    Persons      Males    Females    Persons
              6          38         37         37         38         38
              7         NaN        NaN        NaN        NaN        NaN
              8         NaN        NaN        NaN        NaN        NaN
              9      691079    1421050     752142     712638    1464779
              10     657360    1351921     771055     731592    1502646
              11     667746    1371054     717629     679553    1397183
              12     683420    1405798     727677     693915    1421595
              13     719555    1460674     795423     771369    1566793
              14     758771    1513236     824084     840525    1664602
              15     734122    1453775     839821     864026    1703847
              16     773020    1520138     773132     788548    1561679
              17     788310    1542879     777702     805551    1583257
              18     763180    1504143     773170     808282    1581455
              19     735662    1447404     748954     774601    1523551
              20     659406    1297244     709115     745214    1454332
              21     608231    1206116     632357     667048    1299397
              22     463899     919319     581230     607766    1188999
              23     365398     708090     431325     456390     887716
              24     292333     545263     307441     345217     652657
              25     248695     436937     204026     256529     460549
              26     263518     402681     180351     306494     486842
              27   10873705   21507719   11546638   11855248   23401892
              28        NaN        NaN        NaN        NaN        NaN
              29        NaN        NaN        NaN        NaN        NaN
              30        NaN        NaN        NaN        NaN        NaN

In [10]:
 snapshot.head()

AttributeError: 'collections.OrderedDict' object has no attribute 'head'